export const storeProducts = [
  {
    id: 1,
    title: "Teff white, brown",
    img: "img/teffM.jpeg",
    price: 45.0,
    company: "Ethio African",
    info: "we have your choice of the most important ingredient to make injera, the price is per bag, please order ahead as we have limited supplies",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "raw beef",
    img: "img/beefR.jpeg",
    price: 6.0,
    company: "Ethio African",
    info: "Our premium fresh cut beef, price is per pound",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "imported kotcho",
    img: "img/kotcho.webp",
    price: 9.0,
    company: "Ethio African",
    info: "we import quality organic kotcho from the origin. Price is per bag",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "injera",
    img: "img/injera.jpeg",
    price: 10.0,
    company: "Ethio African",
    info: "Our injera is tasty and made with 100% teff",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Our style sambusa",
    img: "img/sambusa.jpeg",
    price: 1.0,
    company: "Ethio African",
    info: "our sambusa is delicous. ppp",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Spices",
    img: "img/spices.jpeg",
    price: 10.0,
    company: "Ethio African",
    info: "Our spices collection",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "African pottery, can be use for burn incense, & decorations",
    img: "img/ethiopian.jpeg",
    price: 16.0,
    company: "Ethio African",
    info: "sold exlusively in our store",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: " many selection of spices",
    img: "img/ethioAfrican.jpeg",
    price: 3.0,
    company: "Ethio African",
    info: "we have many spices to select from",
    inCart: false,
    count: 0,
    total: 0,
  },
];
export const detailProduct = {
  id: 1,
  title: "Our top pics",
  img: "img/soft-drinks.jpeg",
  price: 11.0,
  company: "Ethio African",
  info: "",
  inCart: false,
  count: 0,
  total: 0,
};
[
  {
    id: 8,
    title: "",
    img: "img/ethioAfrican.jpeg",
    price: 12.99,
    company: "Ethio African",
    info: "",
    inCart: false,
    count: 0,
    total: 0,
  },
];
