export const storeProducts = [
  {
    id: 1,
    title: "Muan Mans shirt",
    img: "img/product-1.jpg",
    price: 19.0,
    company: "Muan Desgin LLC",
    info: "65% POLYSTER 35%COTTON.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Our best sold",
    img: "img/product-2.jpg",
    price: 16.0,
    company: "Muan Desgin LLC",
    info: "made from cotton quality design and comfort.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Muan COLL",
    img: "img/product-3.jpg",
    price: 18.0,
    company: "Muan Desgin LLC",
    info: "65% POLYSTER 35%COTTON.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Maun ladys",
    img: "img/product-4.jpg",
    price: 18.0,
    company: "Muan Desgin LLC",
    info: "75% POLYSTER 25%COTTON.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Muan's kids collection",
    img: "img/product-9.jpg",
    price: 13.0,
    company: "Muan Desgin LLC",
    info: "65% POLYSTER 35%COTTON.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Muan unisex",
    img: "img/product-6.jpg",
    price: 17.0,
    company: "Muan Desgin LLC",
    info: "65% POLYSTER 35%COTTON.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Muan best",
    img: "img/product-7.jpg",
    price: 16.0,
    company: "Muan Desgin LLC",
    info: "65% POLYSTER 35%COTTON.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Muan selection",
    img: "img/product-8.jpg",
    price: 12.0,
    company: "Muan Desgin LLC",
    info: "65% POLYSTER 35%COTTON.",
    inCart: false,
    count: 0,
    total: 0,
  },
];
export const detailProduct = {
  id: 1,
  title: "Our top pics",
  img: "img/product-1.jpg",
  price: 11.0,
  company: "Muan Desgin LLC",
  info: "65% POLYSTER 35%COTTON.",
  inCart: false,
  count: 0,
  total: 0,
};
[
  {
    id: 8,
    title: "Muan selection",
    img: "img/product-8.jpg",
    price: 12.99,
    company: "Muan Desgin LLC",
    info: "65% POLYSTER 35%COTTON.",
    inCart: false,
    count: 0,
    total: 0,
  },
];
